### ISSUE TITLE
Adicionar banco pan

### ISSUE THREAD

**Issue by blap** [wiipowerpc/ppbpass#1]
Parabéns pelo módulo!
Peço a gentileza de incluir o banco pan no módulo.
E se não for pedir muito, me ensina como você acha as coisas nos apps pra poder fazer funcionar que eu ajudo a colocar mais apps aqui.
Obrigado!

**Comment by Hokudan182br** [comment]
Gostaria de colaborar financeiramente para este projeto

**Comment by wiipowerpc** [comment]
> Parabéns pelo módulo! Peço a gentileza de incluir o banco pan no módulo. E se não for pedir muito, me ensina como você acha as coisas nos apps pra poder fazer funcionar que eu ajudo a colocar mais apps aqui. Obrigado!

**Comment by wiipowerpc** [comment]
> Parabéns pelo módulo! Peço a gentileza de incluir o banco pan no módulo. E se não for pedir muito, me ensina como você acha as coisas nos apps pra poder fazer funcionar que eu ajudo a colocar mais apps aqui. Obrigado!

Perdão pela demora (essa conta é secundaria e acabo n lendo emails/notificações q chegam nela), no caso do Banco Pan ele n me aparenta estar fazendo nada de complexo (como o C6, Inter ou Magalu), voce lembrou de esconder o app do magisk nas configurações? Esta passando na SafetyNet? 

Eu analizei o apk dele aqui e a verificação de root dele n passa de simplesmente procurar uns apps como lucky patcher, app quarentine, Magisk (pelo nome original e n o escondido) e os caminhos genericos de root (q o magiskhide ja lida automaticamente)

**Comment by zoide6666** [comment]
Eu também estou com o mesmo problema no Banco Pan com o celular rooteado!
O app tá escondido usando o magisk hide, o celular passa no SafetyNet, estou usando a opção de esconder o magisk (magiskhide - que muda o nome do app) e não tenho nenhum dos app (lucky patcher, etc) citados...
Imagino então que o banco pan deva estar usando outro tipo de checagem de root...

De qualquer forma, parabéns pelo módulo e muito obrigado pela ajuda!

**Comment by wiipowerpc** [comment]
> Eu também estou com o mesmo problema no Banco Pan com o celular rooteado! O app tá escondido usando o magisk hide, o celular passa no SafetyNet, estou usando a opção de esconder o magisk (magiskhide - que muda o nome do app) e não tenho nenhum dos app (lucky patcher, etc) citados... Imagino então que o banco pan deva estar usando outro tipo de checagem de root...
> 
> De qualquer forma, parabéns pelo módulo e muito obrigado pela ajuda!

Sabe me informar se sua ROM roda com selinux permissivo ou impondo? e que modulos voce tem instalado?

**Comment by zoide6666** [comment]
Eu acho que está usando Enforcing... Não sei exatamente como descobrir isso, mas analisando /sys/fs/selinux/enforce está com o valor 1.
Os módulos que tenho no Magisk:
- brbpass
- ExSDCard Access Enabler
- Systemless hosts

Ps.: Estou usando o magisk stable 23.0.

**Comment by wiipowerpc** [comment]
> Eu acho que está usando Enforcing... Não sei exatamente como descobrir isso, mas analisando /sys/fs/selinux/enforce está com o valor 1. Os módulos que tenho no Magisk:
> 
> * brbpass
> * ExSDCard Access Enabler
> * Systemless hosts
> 
> Ps.: Estou usando o magisk stable 23.0.

Pra descobrir o Selinux rode o seguinte comando SEM ROOT no termux

cat /sys/fs/selinux/enforce

Se retornar um resultado então o impondo é falso, se falhar então tá certo

**Comment by zoide6666** [comment]
Retorno do comando sem SU (não root):
cat: /sys/fs/selinux/enforce: Permission denied

**Comment by wiipowerpc** [comment]
> Retorno do comando sem SU (não root): cat: /sys/fs/selinux/enforce: Permission denied

Qual sua versão do Android?

**Comment by zoide6666** [comment]
10 QKQ1.190828.002

**Comment by wiipowerpc** [comment]
> 10 QKQ1.190828.002

Quais apps você tem q usam root? E usando um gerenciador de arquivos pode me dizer que permissões o arquivo enforce tem? (De preferência os 3 números como 664, 660, 440 ou algo assim)

**Comment by zoide6666** [comment]
Aplicativos com root (lista retirada do próprio Magisk):

AdAway
Cx File Explorer
Genos Profile
Gary-Switch
Migrate Flasher
Migrate-GPE
Nova7
Root Browser
Root Checker Basic
SmartPack-Kernel Manager
Termux
Vanced Manager

Permissões "enforce": 640 (-rw-r-----)

**Comment by wiipowerpc** [comment]
> Aplicativos com root (lista retirada do próprio Magisk):
> 
> AdAway Cx File Explorer Genos Profile Gary-Switch Migrate Flasher Migrate-GPE Nova7 Root Browser Root Checker Basic SmartPack-Kernel Manager Termux Vanced Manager
> 
> Permissões "enforce": 640 (-rw-r-----)

Mude o enforce pra 644, o Pan crasha se o enforce está com 640

**Comment by zoide6666** [comment]
Era isso mesmo!!!! Perfeito!

Agora só preciso deixar essa permissão fixa pois preciso fazer o chmod 644 pro enforce pra cada vez que reinicio o celular... Depois dou uma procurada pra achar a melhor forma de fazer isso!

Muito obrigado pela ajuda!!

**Comment by wiipowerpc** [comment]
> Era isso mesmo!!!! Perfeito!
> 
> Agora só preciso deixar essa permissão fixa pois preciso fazer o chmod 644 pro enforce pra cada vez que reinicio o celular... Depois dou uma procurada pra achar a melhor forma de fazer isso!
> 
> Muito obrigado pela ajuda!!

Beleza, vou adicionar isso nativamente no meu modulo, isso deve ajudar com outros bancos tbm q estavam falhando por nenhum motivo certo

**Comment by zoide6666** [comment]
Legal. Se precisar que seja feito algum teste, só me avisar!

**Comment by wiipowerpc** [comment]
> Legal. Se precisar que seja feito algum teste, só me avisar!

Ja lancei a versão 1.8, so testar ai

**Comment by zoide6666** [comment]
Funcionou o banco Pan mesmo reiniciando o celular.
Testados aqui e funcionando: PicPay, C6 e Banco Pan!!

**Comment by wiipowerpc** [comment]
> Funcionou o banco Pan mesmo reiniciando o celular. Testados aqui e funcionando: PicPay, C6 e Banco Pan!!

Top, vlw por testar

**Comment by blap** [comment]
Obrigado galera!
Vocês são top demais!
